<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="PetriNet" nsURI="http://www.htwg-konstanz.de/spray/petriNet"
    nsPrefix="petriNet">
  <eClassifiers xsi:type="ecore:EClass" name="Place" eSuperTypes="identifiable.ecore#//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="token" upperBound="-1"
        eType="#//Token" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputArc" upperBound="-1"
        eType="#//InputArc"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputArc" upperBound="-1"
        eType="#//OutputArc"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition" eSuperTypes="identifiable.ecore#//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputArc" upperBound="-1"
        eType="#//InputArc"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputArc" upperBound="-1"
        eType="#//OutputArc"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputArc" eSuperTypes="identifiable.ecore#//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="place" upperBound="-1"
        eType="#//Place"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transition" upperBound="-1"
        eType="#//Transition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutputArc" eSuperTypes="identifiable.ecore#//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="place" upperBound="-1"
        eType="#//Place"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transition" upperBound="-1"
        eType="#//Transition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Token" eSuperTypes="identifiable.ecore#//Identifiable"/>
  <eClassifiers xsi:type="ecore:EClass" name="Net" eSuperTypes="identifiable.ecore#//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="place" upperBound="-1"
        eType="#//Place" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="token" upperBound="-1"
        eType="#//Token" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputArc" upperBound="-1"
        eType="#//InputArc" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputArc" upperBound="-1"
        eType="#//OutputArc" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
